version: '3.8'
networks:
  selenoid:
    external: true
services:

  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:latest"
    networks:
      selenoid: null
    ports:
      - "4444:4444"
    volumes:
      - "/Users/yevhenii/Desktop/carina-selenoid-ggr/selenoid/:/etc/selenoid"
      - "/Users/yevhenii/Desktop/carina-selenoid-ggr/selenoid/video:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/yevhenii/Desktop/carina-selenoid-ggr/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    volumes:
      - "$PWD/ggr:/etc/grid-router"
    ports:
      - "8090:8080"
    links:
      - selenoid
    command:
      ["--selenoid-uri", "http://selenoid:4444"]

  ggr:
    container_name: ggr
    image: "aerokube/ggr:latest-release"
    networks:
      - selenoid
    volumes:
      - "$PWD/ggr:/etc/grid-router"
    ports:
      - "4445:4444"

  ggr-ui:
    container_name: ggr-ui
    image: "aerokube/ggr-ui:latest"
    networks:
      - selenoid
    volumes:
      - "$PWD/ggr:/etc/grid-router"
    ports:
      - "8888:8888"
    depends_on:
      - ggr
