version: '3'

networks:
  selenoid:
    external:
      name: selenoid # This assumes the network is already created

services:
  selenoid:
    image: "aerokube/selenoid"
    networks:
      selenoid: null
    container_name: selenoid
    volumes:
      - "$PWD/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid/video:/opt/selenoid/video"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  ggr:
    container_name: ggr
    image: "aerokube/ggr:latest"
    networks:
      - selenoid
    volumes:
      - "$PWD/ggr:/etc/grid-router"
    external_links:
      - selenoid
    ports:
      - "4445:4444"

  ggr-ui:
    container_name: ggr-ui
    image: "aerokube/ggr-ui:latest"
    networks:
      - selenoid
    volumes:
      - "$PWD/ggr:/etc/grid-router"
    external_links:
      - selenoid
    depends_on:
      - ggr
    ports:
      - "8888:8888"